### ISSUE TITLE
Resting animation presists after moving

### ISSUE THREAD

**Issue by Zoboomaku** [ScreteMonge/TestPlugin#10]
Apologies in advance as I have no idea what causes this to happen, but it does happen sporadically enough that it's lead to me keeping the plugin off since I discovered it last month.

![ezgif-5-93aebdc72e](https://github.com/ScreteMonge/TestPlugin/assets/32339249/f376a682-9723-4550-8bb2-c6a49fae07b8)

![restsettings](https://github.com/ScreteMonge/TestPlugin/assets/32339249/3fa2cb4d-c86e-4aae-8063-ce2713b168ae)

After it's started no setting change seems to fix the issue, turning the plugin off does not change anything, but logging out and back in does work.

If it'd help I can keep the plugin on for a couple days and try and notice why it starts

**Comment by ScreteMonge** [comment]
Thanks for sending this. I've noticed it too periodically but have struggled to recreate it; I'll try get it sorted out

Edit: found it out after a bit of digging. Will be fixed next update

**Comment by ScreteMonge** [comment]
This should now be resolved
