### ISSUE TITLE
automatic resting

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [ScreteMonge/TestPlugin#4]
any idea if its within the scope of this plugin to make you automatically rest after a certain amount of idle time? say a minute or 2 of no inputs and your character takes a seat? perhaps even make it customisable on the time before you auto sit?

**Comment by ScreteMonge** [comment]
Thank you for the suggestion! An update just released which contains this, which I've called Auto-Rest. Do check it out

**Comment by Jin-Jiyunsun** [comment]
very nice! thanks for updating it
