### ISSUE TITLE
automatic resting "oversight"? 

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [ScreteMonge/TestPlugin#5]
If you have the auto rest timer quite low, say 30 seconds theres a good chance that it will override the current animation of say, woodcutting.

do you think its possible to check that only the idle animation is playing before intiating the resting animation?

**Comment by ScreteMonge** [comment]
Yep, definite oversight. I've submitted a new PR through for review, so hopefully you'll see it fixed in the next couple days

**Comment by ScreteMonge** [comment]
Should be fixed now
