### ISSUE TITLE
Weapon model on player leaks into Gauntlet

### ISSUE THREAD

**Issue by aitoiaita** [ScreteMonge/TestPlugin#7]
If you rest at the Gauntlet portal and enter, your player model will spawn in the Gauntlet arena holding whatever weapon model you were holding in the lobby.
![image](https://user-images.githubusercontent.com/37233128/201229428-542fd247-4222-4fe6-951c-e1b6066c8169.png)
![image](https://user-images.githubusercontent.com/37233128/201229491-857e9aa5-da56-4c60-ba12-1fa3c7d15003.png)

**Comment by ScreteMonge** [comment]
Issue has been resolved with latest update
